python lal/pref_learning/active_sim_pb.py \
--method=lang \
--data-dir=data/data_pref_learning \
--model-dir=exp/robosuite-img-obs-t5-small_20240508_211847_lr_0.001_schedule_False \
--true-reward-dir=lal/pref_learning/true_rewards/1 \
--traj-encoder=cnn \
--lang-model=t5-small --use-bert-encoder \
--seed=0 \
--use-softmax \
--use-img-obs \
--active=4 --reward=4 --lang=1 \